### ISSUE TITLE
Quick about "NOTICE: ALPHA"

### ISSUE THREAD

**Issue by hassanbabaie** [dimitertodorov/nsg-parser#2]
Hi @dimitertodorov just checking how well the tool works with your testing given you're still calling it alpha?

I've been using the Azure Logstash pluin but it's missed a key feature you added which is the "start date".

Also I assume this doesn't modifiy the original NSG Flow Log contents and just keep a tracker on the machine it's running on?

Just checking before I have a go

Thanks

Hass

**Comment by dimitertodorov** [comment]
Hey, 

Tool works great. We have been using it for months without problems. 
It does not touch any of the contents.

The state is stored locally on the machine running the parser.

We have deployed multiple parsers on the same server by registering each one as an independent service. 

As long as MS doesn't change the format of the files or the directory structure there is no reason it won't work.

If you need any help, don't hesitate to reach out.
